apiVersion: v1
kind: Namespace
metadata:
  name: nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
  namespace: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: pedroschmid2311/nestjs-jaeger:latest
          imagePullPolicy: Always
          ports:
            - name: nestjs
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: AMQP_ENDPOINT
              value: amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local:5672
            - name: AMQP_QUEUE_NAME
              value: jaeger_queue
            - name: DB_HOST
              value: mysql.mysql.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_NAME
              value: jaeger
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.jaeger.svc.cluster.local:14268/api/traces
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs
  namespace: nestjs
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nestjs
  sessionAffinity: None
  type: ClusterIP